---
#------------------------------------------------------------------------------
# ansible-playbook semantic_versioning.yaml
#------------------------------------------------------------------------------
- name: Test semantic_versions.yaml
  hosts: localhost # 💡 Use `localhost` for provisioning playbook
  gather_facts: no
  vars: 
    project_name: "{{ lookup('env','PROJECT') | default('versioning') }}"
    provider: aws
    region: us-west-1
    ise_node_size: small
    ise_semantic_version: 3.2.2
  vars_files:
    - ../vars/ise_common.yaml
  tasks:

    - name: Playbook vars
      ansible.builtin.debug:
        msg: |
          playbook_dir:        {{ playbook_dir }}
          inventory_dir:       {{ inventory_dir }}
          ansible_config_file: {{ ansible_config_file }}

          split:               {{ playbook_dir | split('/') }}
          split-1:             {{ playbook_dir.split('/')[0:-1] | join('/') }}

    - name: Semantic Versions
      vars:
        sem_ver: 1.2.3
      ansible.builtin.debug:
        msg: |
          sem_ver: {{ sem_ver }}
          major: {{ sem_ver.split('.')[0] }}
          minor: {{ sem_ver.split('.')[1] }}
          patch: {{ sem_ver.split('.')[2] }}

    - name: ISE Semantic Versions
      ansible.builtin.debug:
        msg: |
          ise_semantic_version (major.minor.version): {{ ise_semantic_version }}

          Elements:
          major: {{ ise_semantic_version.split('.')[0] }}
          minor: {{ ise_semantic_version.split('.')[1] }}
          patch: {{ ise_semantic_version.split('.')[2] }}

          Types:
          ise_semantic_version | type_debug: {{ ise_semantic_version | type_debug }}
          ise_semantic_version | string | type_debug: {{ ise_semantic_version | string | type_debug }}
          ise_semantic_version[0:3] | type_debug: {{ ise_semantic_version[0:3] | type_debug }} 

          major.minor: {{ ise_semantic_version[0:3] }} 
          major.minor.unpatched: {{ ise_semantic_version[0:3]  + '.0' }}

    - name: ISE Common File Lookups Using Semantic Versions
      ansible.builtin.debug:
        msg: |
          ise_images: {{ ise_images | to_nice_yaml(indent=2) }}
          project_name: "{{ project_name }}"
          provider: {{ provider }}
          region: {{ region }}
          ise_node_size: {{ ise_node_size }}
          instance_type: {{ ise_instances[provider][ise_node_size] }}
          ami: {{ ise_images[provider][region][ ise_semantic_version ] | default('UNDEFINED')}}
          ami (unpatched): {{ ise_images[provider][region][ ise_semantic_version[0:3] + '.0' ] }}

