---
#
# Show cisco.ise.network_access_conditions Template
#

- name: Get network_access_conditions
  cisco.ise.network_access_conditions_info:
    ise_hostname: "{{ ansible_host }}"
    ise_username: "{{ ise_username | default( omit ) }}"
    ise_password: "{{ ise_password | default( omit ) }}"
  register: info

# - name: Show `info`
#   ansible.builtin.debug:
#     var: info
#     verbosity: 1

- name: List .name's
  ansible.builtin.debug:
    msg: "{{ info.ise_response | json_query('[].name') }}"

# - name: Get network_access_conditions by id
#   when: info is defined
#     and info.ise_response | length > 0
#   loop: "{{ info.ise_response }}"
#   cisco.ise.network_access_conditions_info:
#     id: "{{ item.id }}"                       # string
#   register: info

# - name: Get network_access_conditions by name
#   when: info is defined
#     and info.ise_response | length > 0
#   loop: "{{ info.ise_response }}"
#   cisco.ise.network_access_conditions_info:
#     id: "{{ item.name }}"                     # string
#   register: info

# - name: Show `info`
#   ansible.builtin.debug:
#     var: info
#     verbosity: 1

- name: Clear `resources`
  ansible.builtin.set_fact:
    resources: []

- name: Set `resources` and remove `id` and `link` attributes
  when: info is defined
    and info.ise_response | count > 0
  loop: "{{ info.ise_response }}"
  ansible.builtin.set_fact:
    resources: '{{ resources | default([]) + [ item
      | dict2items
      | rejectattr("key", "equalto", "id")
      | rejectattr("key", "equalto", "link")
      | list | items2dict ] }}'

- name: Set `network_access_conditions`
  ansible.builtin.set_fact:
    network_access_conditions: "{{ resources }}"

- name: Set network_access_conditions
  when: resources is defined and resources | count > 0
  ansible.builtin.set_fact:
    network_access_conditions: "{{ resources }}"

- name: To YAML File | {{ dir_ise_configs }}/{{ resource_name }}.yaml
  when: resources is defined
    and resources | count > 0
  delegate_to: localhost
  vars:
    resource_name: network_access_conditions
    resources: "{{ resources }}"
  ansible.builtin.template:
    src: templates/resource_template.j2
    dest: "{{ dir_ise_configs }}/{{ resource_name }}.yaml"
    mode: "0644"
