---
#
# ToDo:     The conditional check 'info.ise_response | count > 0' failed. The error was: error while evaluating conditional (info.ise_response | count > 0): 'dict object' has no attribute 'ise_response'. 'dict object' has no attribute 'ise_response'
#
- name: Get profiler_profile
  cisco.ise.profiler_profile_info:
    ise_hostname: "{{ ansible_host }}"
    ise_username: "{{ ise_username | default( omit ) }}"
    ise_password: "{{ ise_password | default( omit ) }}"
  register: info

- name: List .name's
  ansible.builtin.debug:
    msg: "{{ info.ise_response | json_query('[].name') }}"

- name: Get profiler_profile Details by id
  when:
    - info is defined
    - info.ise_response | count > 0
  loop: "{{ info.ise_response }}"
  cisco.ise.profiler_profile_info:
    id: "{{ item.id }}"
    ise_hostname: "{{ ansible_host }}"
    ise_username: "{{ ise_username | default( omit ) }}"
    ise_password: "{{ ise_password | default( omit ) }}"
  register: info

- name: Clear `resources`
  ansible.builtin.set_fact:
    resources: []

- name: Show profiler_profile Detailed info
  ansible.builtin.debug:
    var: info

# info.results[*].ise_response:
- name: Set `resources` and Remove `id` and `link` Attributes
  when: 
    - info is defined
    - info.results | count > 0
  ansible.builtin.set_fact:
    resources: "{{ info.results | json_query('[].ise_response') | ansible.utils.remove_keys(target=['id','link']) }}"

- name: Set profiler_profile
  when: resources is defined and resources | count > 0
  ansible.builtin.set_fact:
    profiler_profile: "{{ resources }}"

- name: To YAML File | {{ dir_ise_configs }}/{{ resource_name }}.yaml
  when: 
    - resources is defined
    - resources | count > 0
  delegate_to: localhost
  vars:
    resource_name: profiler_profile
    resources: "{{ resources }}"
  ansible.builtin.template:
    src: templates/resource_template.j2
    dest: "{{ dir_ise_configs }}/{{ resource_name }}.yaml"
    mode: "0644"
