---
#
# Show cisco.ise.network_device_group Template
#

- name: Get network_device_group
  cisco.ise.network_device_group_info:
    ise_hostname: "{{ ansible_host }}"
    ise_username: "{{ ise_username | default( omit ) }}"
    ise_password: "{{ ise_password | default( omit ) }}"
  register: info

- name: List .name's
  ansible.builtin.debug:
    msg: "{{ info.ise_response | json_query('[].name') }}"

# - name: List Network Device Groups by Name (YAML)
#   when: info is defined and info != []
#   delegate_to: localhost
#   changed_when: false
#   vars:
#     query: "[*].name"
#   ansible.builtin.shell: 'echo "{{ info.ise_response
#     | community.general.json_query(query)
#     | to_nice_yaml(indent=2) }}" > /dev/tty'

- name: Get network_device_group by id
  when: info is defined
    and info.ise_response | count > 0
  loop: "{{ info.ise_response }}"
  cisco.ise.network_device_group_info:
    id: "{{ item.id }}"
    ise_hostname: "{{ ansible_host }}"
    ise_username: "{{ ise_username | default( omit ) }}"
    ise_password: "{{ ise_password | default( omit ) }}"
  register: info

- name: Clear `resources`
  ansible.builtin.set_fact:
    resources: []

- name: Set `resources` and remove `id` and `link` attributes
  when: info is defined
    and info.results[0].ise_response | count > 0
  loop: "{{ info.results[0].ise_response }}"
  ansible.builtin.set_fact:
    resources: '{{ resources | default([]) + [ item
      | dict2items
      | rejectattr("key", "equalto", "id")
      | rejectattr("key", "equalto", "link")
      | list | items2dict ] }}'

- name: Set network_device_group
  when: resources is defined and resources | count > 0
  ansible.builtin.set_fact:
    network_device_group: "{{ resources }}"

- name: To YAML File | {{ dir_ise_configs }}/{{ resource_name }}.yaml
  when: resources is defined
    and resources | count > 0
  delegate_to: localhost
  vars:
    resource_name: network_device_group
    resources: "{{ resources }}"
  ansible.builtin.template:
    src: templates/resource_template.j2
    dest: "{{ dir_ise_configs }}/{{ resource_name }}.yaml"
    mode: "0644"
