---
#
# Show cisco.ise.guest_smtp_notification_settings Template
#

- name: Get guest_smtp_notification_settings
  cisco.ise.guest_smtp_notification_settings_info:
    ise_hostname: "{{ ansible_host }}"
    ise_username: "{{ ise_username | default( omit ) }}"
    ise_password: "{{ ise_password | default( omit ) }}"
  register: info

# - name: Show `info`
#   ansible.builtin.debug:
#     var: info
#     verbosity: 1

- name: Tablize results
  when: info is defined
    and info.ise_response | count > 0
  delegate_to: localhost
  vars:
    hide: ["link"]
    maxw: 30
    rows: "{{ info.ise_response }}"
    temp: "{{ lookup('template', 'templates/list_of_dicts.j2') }}"
  ansible.builtin.debug:
    msg: "{{ temp }}"

- name: Get guest_smtp_notification_settings by id
  when: info is defined
    and info.ise_response | count > 0
  loop: "{{ info.ise_response }}"
  cisco.ise.guest_smtp_notification_settings_info:
    id: "{{ item.id }}"
    ise_hostname: "{{ ansible_host }}"
    ise_username: "{{ ise_username | default( omit ) }}"
    ise_password: "{{ ise_password | default( omit ) }}"
  register: info

# - name: Show `info`
#   ansible.builtin.debug:
#     var: info
#     verbosity: 1

- name: Clear `resources`
  ansible.builtin.set_fact:
    resources: []

- name: Set `resources` and remove `id` and `link` attributes
  when: info is defined
    and info.results | count > 0
  loop: "{{ info.results }}"
  ansible.builtin.set_fact:
    resources: '{{ resources | default([]) + [ item.ise_response
      | dict2items
      | rejectattr("key", "equalto", "id")
      | rejectattr("key", "equalto", "link")
      | list | items2dict ] }}'

- name: To YAML
  when: resources is defined
    and resources | count > 0
  delegate_to: localhost
  changed_when: false
  ansible.builtin.shell: "echo '\n\n{{ resources | to_nice_yaml(indent=2) }}'> /dev/tty"

- name: To YAML File | {{ dir_ise_configs }}/{{ resource_name }}.yaml
  when: resources is defined
    and resources | count > 0
  delegate_to: localhost
  vars:
    resource_name: guest_smtp_notification_settings
    resources: "{{ resources }}"
  ansible.builtin.template:
    src: templates/resource_template.j2
    dest: "{{ dir_ise_configs }}/{{ resource_name }}.yaml"
    mode: "0644"
