---
- name: Get endpoint_group
  cisco.ise.endpoint_group_info:
    ise_hostname: "{{ ansible_host }}"
    ise_username: "{{ ise_username | default( omit ) }}"
    ise_password: "{{ ise_password | default( omit ) }}"
  register: info

- name: List .name's
  ansible.builtin.debug:
    msg: "{{ info.ise_response | json_query('[].name') }}"

- name: Tablize `info`
  when:
    - info is defined
    - info.ise_response | count > 0
  delegate_to: localhost
  vars:
    hide: ["link"]
    maxw: 40
    rows: "{{ info.ise_response }}"
    temp: "{{ lookup('template', 'templates/list_of_dicts.j2') }}"
  ansible.builtin.debug:
    msg: "{{ temp }}"

- name: Get Resource Details by id
  when:
    - info is defined
    - info.ise_response | count > 0
  loop: "{{ info.ise_response }}"
  cisco.ise.endpoint_group_info:
    id: "{{ item.id }}"
    ise_hostname: "{{ ansible_host }}"
    ise_username: "{{ ise_username | default( omit ) }}"
    ise_password: "{{ ise_password | default( omit ) }}"
  register: info

- name: Clear `resources`
  ansible.builtin.set_fact:
    resources: []

- name: Set `resources` and Remove `id` and `link` Attributes
  when: 
    - info is defined
    - info.results | count > 0
  ansible.builtin.set_fact:
    resources: "{{ info.results | ansible.utils.remove_keys(target=['id','link']) }}"

- name: Set endpoint_group
  when: resources is defined and resources | count > 0
  ansible.builtin.set_fact:
    endpoint_group: "{{ resources }}"

- name: To YAML File | {{ dir_ise_configs }}/{{ resource_name }}.yaml
  when: 
    - resources is defined
    - resources | count > 0
  delegate_to: localhost
  vars:
    resource_name: endpoint_group
    resources: "{{ resources }}"
  ansible.builtin.template:
    src: templates/resource_template.j2
    dest: "{{ dir_ise_configs }}/{{ resource_name }}.yaml"
    mode: "0644"
