---
#
# Show cisco.ise.sxp_vpns Template
#

- name: Get sxp_vpns
  cisco.ise.sxp_vpns_info:
    ise_hostname: "{{ ansible_host }}"
    ise_username: "{{ ise_username | default( omit ) }}"
    ise_password: "{{ ise_password | default( omit ) }}"
  register: info

# - name: Show `info`
#   ansible.builtin.debug:
#     var: info
#     verbosity: 1

- name: List .name's
  ansible.builtin.debug:
    msg: "{{ info.ise_response | json_query('[].name') }}"

- name: Get sxp_vpns by id
  when: info is defined
    and info.ise_response | count > 0
  loop: "{{ info.ise_response }}"
  cisco.ise.sxp_vpns_info:
    id: "{{ item.id }}"
    ise_hostname: "{{ ansible_host }}"
    ise_username: "{{ ise_username | default( omit ) }}"
    ise_password: "{{ ise_password | default( omit ) }}"
  register: info

#----------------------------------------------------------------------------
# Example egress_matrix_cell_info output
#----------------------------------------------------------------------------
# info:
#   results:
#   - ise_response:
#       id: bc4bc9a7-5d15-4c34-8086-49b56a0e8736
#       link:
#         href: https://198.18.133.27/ers/config/sxpvpns/bc4bc9a7-5d15-4c34-8086-49b56a0e8736
#         rel: self
#         type: application/json
#       sxpVpnName: default
#----------------------------------------------------------------------------

# - name: Show `info`
#   ansible.builtin.debug:
#     var: info
#     verbosity: 1

- name: Clear `resources`
  ansible.builtin.set_fact:
    resources: []

- name: Set `resources` and remove `id` and `link` attributes
  when: info is defined
    and info.results | count > 0
  loop: "{{ info.results }}"
  ansible.builtin.set_fact:
    resources: '{{ resources | default([]) + [ item.ise_response
      | dict2items
      | rejectattr("key", "equalto", "id")
      | rejectattr("key", "equalto", "link")
      | list | items2dict ] }}'

- name: Set sxp_vpns
  when: resources is defined and resources | count > 0
  ansible.builtin.set_fact:
    sxp_vpns: "{{ resources }}"

- name: To YAML File | {{ dir_ise_configs }}/{{ resource_name }}.yaml
  when: resources is defined
    and resources | count > 0
  delegate_to: localhost
  vars:
    resource_name: sxp_vpns
    resources: "{{ resources }}"
  ansible.builtin.template:
    src: templates/resource_template.j2
    dest: "{{ dir_ise_configs }}/{{ resource_name }}.yaml"
    mode: "0644"
