---
- name: Get network_access_local_exception_rules_info by Policy Set id
  when:
    - network_access_policy_set is defined
    - network_access_policy_set | count > 0
  loop: "{{ network_access_policy_set }}"
  cisco.ise.network_access_local_exception_rules_info:
    ise_hostname: "{{ ansible_host }}"
    ise_username: "{{ ise_username | default( omit ) }}"
    ise_password: "{{ ise_password | default( omit ) }}"
    policyId: "{{ item.id }}" # Policy Set ID
  register: info


- name: Show `info`
  ansible.builtin.debug:
    var: info

- name: Clear `resources`
  ansible.builtin.set_fact:
    resources: []

# info.results[*].ise_response:
- name: Set `resources` and Remove `id` and `link` Attributes
  when: 
    - info is defined
    - info.results | count > 0
  ansible.builtin.set_fact:
    resources: "{{ info.results | json_query('[].ise_response') | ansible.utils.remove_keys(target=['id','link']) }}"

- name: To YAML File | {{ dir_ise_configs }}/{{ resource_name }}.yaml
  when:
    - resources is defined
    - resources | count > 0
  delegate_to: localhost
  vars:
    resource_name: network_access_local_exception_rules
    resources: "{{ resources }}"
  ansible.builtin.template:
    src: templates/resource_template.j2
    dest: "{{ dir_ise_configs }}/{{ resource_name }}.yaml"
    mode: "0644"

- name: Set network_access_local_exception_rules
  when:
    - resources is defined
    - resources | count > 0
  ansible.builtin.set_fact:
    network_access_local_exception_rules: "{{ resources }}"
