---
#
# Show cisco.ise.egress_matrix_cell Template
#

- name: Get egress_matrix_cell
  cisco.ise.egress_matrix_cell_info:
    ise_hostname: "{{ ansible_host }}"
    ise_username: "{{ ise_username | default( omit ) }}"
    ise_password: "{{ ise_password | default( omit ) }}"
  register: info

# - name: Show `info`
#   ansible.builtin.debug:
#     var: info
#     verbosity: 1

- name: List .name's
  ansible.builtin.debug:
    msg: "{{ info.ise_response | json_query('[].name') }}"

- name: Tablize `info`
  when: info is defined
    and info.ise_response | count > 0
  delegate_to: localhost
  vars:
    hide: ["link"]
    maxw: 40
    rows: "{{ info.ise_response }}"
    temp: "{{ lookup('template', 'templates/list_of_dicts.j2') }}"
  ansible.builtin.debug:
    msg: "{{ temp }}"

- name: Get egress_matrix_cell by id
  when: info is defined
    and info.ise_response | count > 0
  loop: "{{ info.ise_response }}"
  cisco.ise.egress_matrix_cell_info:
    id: "{{ item.id }}"
    ise_hostname: "{{ ansible_host }}"
    ise_username: "{{ ise_username | default( omit ) }}"
    ise_password: "{{ ise_password | default( omit ) }}"
  register: info

#----------------------------------------------------------------------------
# Example egress_matrix_cell_info output
#----------------------------------------------------------------------------
# info:
#   results:
#   - ise_response:
#       defaultRule: PERMIT_IP
#       description: Default egress rule
#       destinationSgtId: 92bb1950-8c01-11e6-996c-525400b48521
#       id: 92c1a900-8c01-11e6-996c-525400b48521
#       link:
#         href: https://198.18.133.27/ers/config/egressmatrixcell/92c1a900-8c01-11e6-996c-525400b48521
#         rel: self
#         type: application/json
#       matrixCellStatus: ENABLED
#       name: ANY-ANY
#       sgacls:
#       - 92951ac0-8c01-11e6-996c-525400b48521
#       sourceSgtId: 92bb1950-8c01-11e6-996c-525400b48521
#----------------------------------------------------------------------------

# - name: Show `info`
#   ansible.builtin.debug:
#     var: info
#     verbosity: 1

- name: Tablize `info`
  when: info is defined
    and info.results | count > 0
  delegate_to: localhost
  vars:
    hide: ["id", "link"]
    maxw: 40
    rows: "{{ info.results | json_query('[].ise_response') }}"
    temp: "{{ lookup('template', 'templates/list_of_dicts.j2') }}"
  ansible.builtin.debug:
    msg: "{{ temp }}"

# - name: Show `info`
#   ansible.builtin.debug:
#     var: info
#     verbosity: 1

- name: Clear `resources`
  ansible.builtin.set_fact:
    resources: []

- name: Set `resources` and remove `id` and `link` attributes
  when: info is defined
    and info.results | count > 0
  loop: "{{ info.results }}"
  ansible.builtin.set_fact:
    resources: '{{ resources | default([]) + [ item.ise_response
      | dict2items
      | rejectattr("key", "equalto", "id")
      | rejectattr("key", "equalto", "link")
      | list | items2dict ] }}'

- name: Set egress_matrix_cell
  when: resources is defined and resources | count > 0
  ansible.builtin.set_fact:
    egress_matrix_cell: "{{ resources }}"

- name: To YAML File | {{ dir_ise_configs }}/{{ resource_name }}.yaml
  when: resources is defined
    and resources | count > 0
  delegate_to: localhost
  vars:
    resource_name: egress_matrix_cell
    resources: "{{ resources }}"
  ansible.builtin.template:
    src: templates/resource_template.j2
    dest: "{{ dir_ise_configs }}/{{ resource_name }}.yaml"
    mode: "0644"
