---
#
# Show cisco.ise.trusted_certificate_export Template
#

- name: Show trusted_certificate
  ansible.builtin.debug:
    var: trusted_certificate
    verbosity: 0

- name: Count Certificates
  ansible.builtin.debug:
    msg: "Certificates Count: {{ trusted_certificate | count }}"
    verbosity: 0

- name: Get trusted_certificate_export
  loop: "{{ trusted_certificate }}"
  cisco.ise.trusted_certificate_export_info:
    ise_hostname: "{{ ansible_host }}"
    ise_username: "{{ ise_username | default( omit ) }}"
    ise_password: "{{ ise_password | default( omit ) }}"
    id: "{{ item.id }}"
  register: trusted_certificate_export

- name: Show trusted_certificate_export
  ansible.builtin.debug:
    var: trusted_certificate_export
    verbosity: 0

# - name: Get trusted_certificate_export by id
#   when: info is defined
#     and info.ise_response | count > 0
#   loop: "{{ info.ise_response }}"
#   cisco.ise.trusted_certificate_export_info:
#     id: "{{ item.id }}"
#     ise_hostname: "{{ ansible_host }}"
    ise_username: "{{ ise_username | default( omit ) }}"
    ise_password: "{{ ise_password | default( omit ) }}"
#   register: info

# - name: Show `info`
#   ansible.builtin.debug:
#     var: info
#     verbosity: 1

# - name: Clear `resources`
#   ansible.builtin.set_fact:
#     resources: []

# - name: Tablize results
#   when: info is defined
#     and info.ise_response | count > 0
#   delegate_to: localhost
#   vars:
#     hide: ["link"]
#     maxw: 30
#     rows: "{{ info.ise_response }}"
#     temp: "{{ lookup('template', 'templates/list_of_dicts.j2') }}"
#   ansible.builtin.debug:
#     msg: "{{ temp }}"

# - name: Set `resources` and remove `id` and `link` attributes
#   when: info is defined
#     and info.results | count > 0
#   loop: "{{ info.results }}"
#   ansible.builtin.set_fact:
#     resources: '{{ resources | default([]) + [ item.ise_response
#       | dict2items
#       | rejectattr("key", "equalto", "id")
#       | rejectattr("key", "equalto", "link")
#       | list | items2dict ] }}'
#   ignore_errors: true

# - name: Set trusted_certificate_export
#   when: resources is defined and resources | count > 0
#   ansible.builtin.set_fact:
#     trusted_certificate_export: "{{ resources }}"

# - name: To YAML File | {{ dir_ise_configs }}/{{ resource_name }}.yaml
#   when: resources is defined
#     and resources | count > 0
#   delegate_to: localhost
#   vars:
#     resource_name: trusted_certificate_export
#     resources: "{{ resources }}"
#   ansible.builtin.template:
#     src: templates/resource_template.j2
#     dest: "{{ dir_ise_configs }}/{{ resource_name }}.yaml"
#     mode: "0644"


#------------------------------------------------------------------------------
# trusted_certificate_export_info – Export Trusted Certificate(s)
#------------------------------------------------------------------------------

- name: Export Trusted Certificate(s) | {{ inventory_hostname }}
  when: trusted_certificate_export is defined
    and trusted_certificate_export | count > 0
  loop: "{{ trusted_certificate_export }}"
  cisco.ise.trusted_certificate_export_info:
    id: "{{ item.id }}"
    # dirPath: "{{ dir_trusted_certs }}/exported"
    dirPath: "./files/certificates/exported/trusted/"
    filename: "{{ item.issuedTo }}.pem" # exports as PEM file
    saveFile: true # automatic file creation of raw response
    # mode: "0644"
