---
#
# Show cisco.ise.self_registered_portal Template
#

- name: Get self_registered_portal
  cisco.ise.self_registered_portal_info:
    ise_hostname: "{{ ansible_host }}"
    ise_username: "{{ ise_username | default( omit ) }}"
    ise_password: "{{ ise_password | default( omit ) }}"
  register: info

# - name: Show `info`
#   ansible.builtin.debug:
#     var: info
#     verbosity: 1

- name: List .name's
  ansible.builtin.debug:
    msg: "{{ info.ise_response | json_query('[].name') }}"

- name: Get self_registered_portal by id
  when: info is defined
    and info.ise_response | count > 0
  loop: "{{ info.ise_response }}"
  cisco.ise.self_registered_portal_info:
    id: "{{ item.id }}"
    ise_hostname: "{{ ansible_host }}"
    ise_username: "{{ ise_username | default( omit ) }}"
    ise_password: "{{ ise_password | default( omit ) }}"
  register: info

# - name: Show `info`
#   ansible.builtin.debug:
#     var: info
#     verbosity: 1

- name: Clear `resources`
  ansible.builtin.set_fact:
    resources: []

- name: Set `resources` and remove `id` and `link` attributes
  when: info is defined
    and info.results[0].ise_response | count > 0
  loop: "{{ info.results[0].ise_response }}"
  ansible.builtin.set_fact:
    resources: '{{ resources | default([]) + [ item
      | dict2items
      | rejectattr("key", "equalto", "id")
      | rejectattr("key", "equalto", "link")
      | list | items2dict ] }}'

- name: Set self_registered_portal
  when: resources is defined and resources | count > 0
  ansible.builtin.set_fact:
    self_registered_portal: "{{ resources }}"

- name: To YAML File | {{ dir_ise_configs }}/{{ resource_name }}.yaml
  when: resources is defined
    and resources | count > 0
  delegate_to: localhost
  vars:
    resource_name: self_registered_portal
    resources: "{{ resources }}"
  ansible.builtin.template:
    src: templates/resource_template.j2
    dest: "{{ dir_ise_configs }}/{{ resource_name }}.yaml"
    mode: "0644"
