---
- name: Get network_access_conditions_for_policy_set
  cisco.ise.network_access_conditions_for_policy_set_info:
    ise_hostname: "{{ ansible_host }}"
    ise_username: "{{ ise_username | default( omit ) }}"
    ise_password: "{{ ise_password | default( omit ) }}"
  register: info

- name: List .name's
  ansible.builtin.debug:
    msg: "{{ info.ise_response | json_query('[].name') }}"

#
# ⚠ Cannot easily make a table from the mixed data types in the response list!
#
# - name: Summarize results
#   when: info is defined
#     and info.ise_response | count > 0
#   delegate_to: localhost
#   vars:
#     # hide: ['id','allowedValues']
#     maxw: 30
#     rows: "{{ info.ise_response }}"
#     temp: "{{ lookup('template', 'templates/list_of_dicts.j2') }}"
#   ansible.builtin.shell: "echo '{{ temp }}' > /dev/tty"

- name: Clear `resources`
  ansible.builtin.set_fact:
    resources: []

- name: Set `resources` and Remove `id` and `link` Attributes
  when: 
    - info is defined
    - info.ise_response | count > 0
  ansible.builtin.set_fact:
    resources: "{{ info.ise_response | ansible.utils.remove_keys(target=['id','link']) }}"


- name: Tablize info
  when: 
    - resources is defined
    - resources | count > 0
  delegate_to: localhost
  vars:
    # hide: ["id", "allowedValues"]
    maxw: 30
    rows: "{{ resources }}"
    temp: "{{ lookup('template', 'templates/list_of_dicts.j2') }}"
  ansible.builtin.debug:
    msg: "{{ temp }}"

- name: Set network_access_conditions_for_policy_set
  when: resources is defined and resources | count > 0
  ansible.builtin.set_fact:
    network_access_conditions_for_policy_set: "{{ resources }}"

- name: Write network_access_conditions_for_policy_set Configuration to YAML file
  when: 
    - resources is defined
    - resources | count > 0
  delegate_to: localhost
  vars:
    resource_name: network_access_conditions_for_policy_set
    resources: "{{ resources }}"
  ansible.builtin.template:
    src: templates/resource_template.j2
    dest: "{{ dir_ise_configs }}/{{ resource_name }}.yaml"
    mode: "0644"
