---

- name: Reset `resources`
  ansible.builtin.set_fact:
    resource_name: guest_smtp_notification_settings
    resources: []

- name: Get {{ resource_name }}
  cisco.ise.guest_smtp_notification_settings_info:
    ise_hostname: "{{ ansible_host }}"
    ise_username: "{{ ise_username | default( omit ) }}"
    ise_password: "{{ ise_password | default( omit ) }}"
  register: info

- name: Tablize {{ resource_name }}
  when:
    - info is defined
    - info.ise_response | count > 0
  delegate_to: localhost
  vars:
    hide: ['link']
    maxw: 30
    rows: "{{ info.ise_response }}"
    temp: "{{ lookup('template', 'templates/list_of_dicts.j2') }}"
  ansible.builtin.debug:
    msg: "{{ temp }}"

- name: Get {{ resource_name }} Details by id
  when:
    - info is defined
    - info.ise_response | count > 0
  loop: "{{ info.ise_response }}"
  cisco.ise.guest_smtp_notification_settings_info:
    id: "{{ item.id }}"
    ise_hostname: "{{ ansible_host }}"
    ise_username: "{{ ise_username | default( omit ) }}"
    ise_password: "{{ ise_password | default( omit ) }}"
  register: info

- name: Set `resources` and Remove `link` Attribute
  when: 
    - info is defined
    - info.results | count > 0
  ansible.builtin.set_fact:
    resources: "{{ info.results | community.general.json_query('[].ise_response') | ansible.utils.remove_keys(target=['link']) }}"

- name: To YAML | {{ resource_name }}
  when:
    - resources is defined
    - resources | count > 0
  delegate_to: localhost
  changed_when: false
  ansible.builtin.shell: "echo '{{ resource_name }}:\n{{ resources | to_nice_yaml(indent=2) }}'> /dev/tty"

- name: To YAML File | {{ dir_ise_configs_show }}/{{ resource_name }}.yaml
  when:
    - resources is defined
    - resources | count > 0
  delegate_to: localhost
  ansible.builtin.template:
    src: templates/resource_template.j2
    dest: "{{ dir_ise_configs_show }}/{{ resource_name }}.yaml"
    mode: "0644"

- name: Set {{ resource_name }}
  when:
    - resources is defined
    - resources | count > 0
  ansible.builtin.set_fact:
    guest_smtp_notification_settings: "{{ resources }}"
