---

- name: Not Implemented
  delegate_to: localhost
  ansible.builtin.debug:
    msg: |
      ░
      ░       /\
      ░      /  \
      ░     / ❕ \    {{ resource_name | default('') }} Not Implemented
      ░    /______\
      ░
      ░
