---

- name: Reset `resources`
  ansible.builtin.set_fact:
    resource_name: system_certificates
    resources: []

- name: Get {{ resource_name }}
  cisco.ise.system_certificate_info:
    ise_hostname: "{{ ansible_host }}"
    ise_username: "{{ ise_username | default( omit ) }}"
    ise_password: "{{ ise_password | default( omit ) }}"
    hostName: "{{ inventory_hostname }}"
    # id: "{{ item.id }}"
  register: info

- name: List .name's
  ansible.builtin.debug:
    msg: "{{ info.ise_response | community.general.json_query('[].issuedTo') }}"

- name: Set `resources` and Remove `link` Attribute
  when: 
    - info is defined
    - info.ise_response | count > 0
  ansible.builtin.set_fact:
    resources: "{{ info.ise_response | ansible.utils.remove_keys(target=['link']) }}"

- name: To YAML | {{ resource_name }}
  when:
    - resources is defined
    - resources | count > 0
  delegate_to: localhost
  changed_when: false
  ansible.builtin.shell: "echo '{{ resource_name }}:\n{{ resources | to_nice_yaml(indent=2) }}'> /dev/tty"

- name: To YAML File | {{ dir_ise_show_configs }}/{{ resource_name }}.yaml
  when:
    - resources is defined
    - resources | count > 0
  delegate_to: localhost
  ansible.builtin.template:
    src: templates/resource_template.j2
    dest: "{{ dir_ise_show_configs }}/{{ resource_name }}.yaml"
    mode: "0644"

- name: Set {{ resource_name }}
  when:
    - resources is defined
    - resources | count > 0
  ansible.builtin.set_fact:
    system_certificates: "{{ resources }}"

#------------------------------------------------------------------------------
# Export System Certificate to local directory
#------------------------------------------------------------------------------

- name: Create directory `{{ dir_ise_show_certs_system }}`
  delegate_to: localhost
  ansible.builtin.file:
    path: "{{ dir_ise_show_certs_system }}"
    state: directory
    mode: "0700"

# ToDo:   msg: 'An error occured when executing operation. The error was: {''id'': ''8ad91e94-0d16-4fbf-83ad-0923e371f56b'', ''password'': ''ISEisC00L''} is invalid. Reason: data must contain [''export''] properties'
# - name: Export {{ system_certificates | count }} System Certificates | {{ inventory_hostname }}
#   when: system_certificates is defined
#     and system_certificates | count > 0
#   loop: "{{ system_certificates }}"
#   cisco.ise.system_certificate_export_info:
#     ise_hostname: "{{ ansible_host }}"
#     ise_username: "{{ ise_username | default( omit ) }}"
#     ise_password: "{{ ise_password | default( omit ) }}"
#     id: "{{ item.id }}"
#     saveFile: true # automatic file creation of raw response
#     dirPath: "{{ dir_ise_show_certs_system }}"
#     filename: "{{ item.issuedTo }}.pem" # exports as PEM file
#     # export: # ??? System Certificate Export Info’s export ???
#     password: "{{ ise_system_certificate_password }}"
#   register: system_certificates_export
