---
#------------------------------------------------------------------------------
# ISE Deploy Playbook
#------------------------------------------------------------------------------
- name: ISE Deploy Playbook
  hosts: ise
  gather_facts: no
  vars:
  vars_files: vars/main.yaml
  roles:

    - ise_login_await # ISE SSH & HTTPS for CLI & GUI Login Page

    # Roles & Services: Join deployment and assign node roles, services, node groups, ...
    - ise_node_standalone
    # - ise_node_deployment
    # - ise_node_ppan
    # - ise_node_deployed_by_tags_⚠

    - name: ISE is Deployed!
      role: banner
      vars:
        banner_name: cisco_secure_ise_logo_small
        banner_text: ISE is Deployed!
