---
#------------------------------------------------------------------------------
# Cisco Identity Services Engine (ISE) Show Playbook
#
# Example commands:
#   ansible-playbook ise.show.yaml -v     # 💡 verbosity == 1 to show all task output automatically
#   ansible-playbook ise.show.yaml --tags certs
#   ansible-playbook -i inventory/dcloud_ise_sandbox.yaml --limit ise ise.show.yaml --tags backup
#------------------------------------------------------------------------------
- name: ISE Show Playbook
  hosts: ise
  gather_facts: no
  vars:
  vars_files: vars/main.yaml
  roles:
    - ise_show
