---
- name: ISE Facts Role
  hosts: ise
  gather_facts: no
  vars:
  roles:
    # - ise_login_await
    - ise_facts # gather ISE version, patch, & node info
    - ise_facts_table # show ISE nodes' facts in a table

  tasks:
    - name: Count ISE nodes
      ansible.builtin.debug:
        msg: "{{ ise_facts | count }} ISE Nodes"

    - name: Filter ISE facts for {{ inventory_hostname }}
      ansible.builtin.set_fact:
        ise_node_facts: "{{ ise_facts | selectattr('name', 'equalto', inventory_hostname ) | first }}"

    - ansible.builtin.debug:
        msg: |
          ise_node_facts.version_major: {{ ise_node_facts.version_major }}
          ise_node_facts.version_minor: {{ ise_node_facts.version_minor }}
          ise_node_facts.version_release: {{ ise_node_facts.version_release }}
          ise_node_facts.version_build: {{ ise_node_facts.version_build }}
          ise_node_facts.version: {{ ise_node_facts.version }}
          ise_node_facts.version_semantic: {{ ise_node_facts.version_semantic }}

          patches: "{{ ise_node_facts.patches }}"
          unpatched: "{{ ise_node_facts.unpatched }}"
          patch: "{{ ise_node_facts.patch }}"

          nodeStatus: "{{ ise_node_facts.nodeStatus }}"
          roles: "{{ ise_node_facts.roles }}"
          services: "{{ ise_node_facts.services }}"
