---
- name: ISE Facts Role
  hosts: all
  gather_facts: no
  vars_files:
    - vars/main.yaml
  roles:
    - ise_login_await
    - ise_facts # gather ISE version, patch, & node info
    - ise_facts_table # show ISE nodes' facts in a table

  tasks:
    - ansible.builtin.debug:
        msg: "List items: {{ ise_facts | count }}"

    # - ansible.builtin.debug:
    #     msg: "ise_facts[0].displayName ({{ ise_facts[0].version }}) is <= ISE 3.1"
    #   when: ise_facts[0].version is version('3.1', '<=')
    # - ansible.builtin.debug:
    #     msg: "ise_facts[0].displayName ({{ ise_facts[0].version }}) is > ISE 3.1"
    #   when: ise_facts[0].version is version('3.1', '>')
    # - ansible.builtin.debug:
    #     msg: "ise_facts[0].displayName ({{ ise_facts[0].version }}) is == ISE 3.1"
    #   when: ise_facts[0].version is version('3.1', '==')
    # - ansible.builtin.debug:
    #     msg: "ise_facts[0].displayName ({{ ise_facts[0].version }}) is == ISE 3.1"
    #   when: ise_facts[0].version_major | int == 3
    #     and ise_facts[0].version_minor | int == 1

    - name: Filter ISE facts for {{ inventory_hostname }}
      ansible.builtin.set_fact:
        ise_node_facts: "{{ ise_facts | selectattr('name', 'equalto', inventory_hostname ) | first}}"

    - name: Show `ise_node_facts`
      ansible.builtin.debug:
        var: ise_node_facts
        verbosity: 1
    - ansible.builtin.debug:
        msg: |
          ise_node_facts.version_major: {{ ise_node_facts.version_major }}
          ise_node_facts.version_minor: {{ ise_node_facts.version_minor }}
          ise_node_facts.version_release: {{ ise_node_facts.version_release }}
          ise_node_facts.version_build: {{ ise_node_facts.version_build }}

          patches: "{{ ise_node_facts.patches }}"
          unpatched: "{{ ise_node_facts.unpatched }}"
          patch: "{{ ise_node_facts.patch }}"

          nodeStatus: "{{ ise_node_facts.nodeStatus }}"
          roles: "{{ ise_node_facts.roles }}"
          services: "{{ ise_node_facts.services }}"
