---
#------------------------------------------------------------------------------
# ISE Eternal Evaluation (ISEEE) - Provision Playbook
# VPC(s), Networks, VPNs, ISE Nodes, Patch + Hotpatches, …
#------------------------------------------------------------------------------
- name: ISE Eternal Evaluation (ISEEE) - Provision
  hosts: localhost # 💡 Use `localhost` for provisioning playbook
  gather_facts: no
  vars:
    # required for initial provisioning
    ise_username: "{{ lookup('env','ISE_USERNAME') | default( omit ) }}"
    ise_password: "{{ lookup('env','ISE_PASSWORD') | default( omit ) }}" # ⚠ ISE 3.2+ provisioning password must be changed on first login!
  vars_files: vars/iseee.yaml
  roles:

    - ssh_key_local   # 💡 Provision an SSH key for this project

    # Provision ISE in AWS
    - aws_ec2_ssh_keypair_upload        # upload SSH key for EC2 instances
    - aws_ec2_vpc                       # AWS VPC
    - aws_ec2_ise_security_groups       # security group(s) for ISE
    - aws_ec2_ise_nodes                 # see vars/iseee.yaml for node definitions
    - aws_ec2_show                      # see what we provisioned
    - aws_ec2_r53_public_dns_entry      # add ISE nodes to AWS R53 DNS

    # Provision other AWS EC2 instances from Ansible roles ...
    # - ubuntu_vsftpd_⚠
    # - meraki_vmx_aws_⚠
    # - meraki_mx_⚠
    # - meraki_mr_ssid_.corp_⚠
    # - meraki_mr_ssid_.iot_ipsk_⚠

    - refresh_inventory # 💡 must refresh inventory for next playbook!

#------------------------------------------------------------------------------
# Initialize ISEEE : REST APIs, Repository(s)
#------------------------------------------------------------------------------
- name: ISE Eternal Evaluation (ISEEE) - Initialize
  hosts: iseee
  gather_facts: no
  vars:
  vars_files: vars/iseee.yaml
  roles:

    - role: banner
      vars:
        banner_name: hourglass
        banner_line_2: ISE boot times vary by release and instance size.
        banner_line_3: Expect to wait at least 25 minutes...

    - ise_login_await # ISE SSH & HTTPS for CLI & GUI Login Page
    # - ise_cli_password_reset # 💡 unnecessary when doing a restore from backup!
    - ise_cli_dns_service_cache_enabled

    - ise_apis_enabled # ISE ERS & OpenAPIs enabled

    # - ise_repository_localdisk  # LOCALDISK
    # - ise_repository            # configure repository & set `ise_repository_name`
    - ise_repository_from_env     # configure repository & set `ise_repository_name`

    - ise_facts                   # gather ISE version, patch, & node state info
    - ise_facts_table             # summarize ISE nodes' facts in a table

    - name: ISEEE is Provisioned!
      role: banner
      vars:
        banner_name: cisco_iseee_logo_small
        banner_text: ISEEE is Provisioned!
