---
- name: ISE Eternal Evaluation (ISEEE) - Licensing
  hosts: iseee
  gather_facts: no
  vars:
  vars_prompt:
  vars_files:
    - vars/iseee.yaml
  roles:

    # - ise_licensing_status
    # - ise_liensing_eval_expiration_warning

  tasks:


    #
    # 💡 Use `tier-state` REST API instead of cisco.ise.licensing_tier_state_info
    #    If ISE is licensed with a PLR or SLR license there will no no tier-state.
    #    If there is no tier-state, it will return a 404 but that is not handled
    #    well by the cisco.ise.licensing_tier_state_info module.
    #

    - name: Get Licensing Tier State Information | {{ inventory_hostname }} ({{ ansible_host }})
      delegate_to: localhost
      ansible.builtin.uri:
        url: https://{{ ansible_host }}/api/v1/license/system/tier-state
        method: GET
        headers:
          Accept: application/json
        force_basic_auth: true
        url_username: "{{ ise_username }}"
        url_password: "{{ ise_password }}"
        follow_redirects: safe
        # timeout: "{{ wait_uri_timeout }}"
        validate_certs: false
        return_content: yes
        status_code: [200, 404]
      register: ise_license_tier_state

      # Example ise_license_tier_state response:
      # """
      # ise_license_tier_state:
      #   changed: false
      #   failed: false
      #   ise_response:
      #   - compliance: EVALUATION
      #     consumptionCounter: 0
      #     daysOutOfCompliance: '-'
      #     lastAuthorization: '-'
      #     name: ESSENTIAL
      #     status: ENABLED
      #   - compliance: EVALUATION
      #     consumptionCounter: 0
      #     daysOutOfCompliance: '-'
      #     lastAuthorization: '-'
      #     name: ADVANTAGE
      #     status        : ENABLED
      #   - compliance: EVALUATION
      #     consumptionCounter: 0
      #     daysOutOfCompliance: '-'
      #     lastAuthorization: '-'
      #     name: PREMIER
      #     status: ENABLED
      #   - compliance: EVALUATION
      #     consumptionCounter: 0
      #     daysOutOfCompliance: '-'
      #     lastAuthorization: '-'
      #     name: DEVICEADMIN
      #     status: ENABLED
      #   result: ''
      # """

    - name: Get Evaluation Licensing Info | {{ inventory_hostname }} ({{ ansible_host }})
      delegate_to: localhost
      ansible.builtin.uri:
        url: https://{{ ansible_host }}/api/v1/license/system/eval-license
        method: GET
        headers:
          Accept: application/json
        force_basic_auth: true
        url_username: "{{ ise_username }}"
        url_password: "{{ ise_password }}"
        follow_redirects: safe
        # timeout: "{{ wait_uri_timeout }}"
        validate_certs: false
        return_content: yes
        status_code: [200, 404]
      register: ise_eval_license_info

    # Assign a value to ise_licensing_eval_days, default: 0
    - name: Set `ise_licensing_eval_days`
      ansible.builtin.set_fact:
        ise_licensing_eval_days: "{{ ise_eval_license_info.json.daysRemaining | int | default(0) }}"
      ignore_errors: true

    - name: ISE Evaluation Expired!
      when: ise_license_eval_days is defined
        and ise_license_eval_days | int <= 0
      vars:
        bar: "░  "
      ansible.builtin.debug:
        msg: |
          {{bar}} 
          {{bar}}      .          
          {{bar}}     /|\          _   ___   ___   ___   ___  
          {{bar}} @  /|||\  @     | | / __| | __| | __| | __|
          {{bar}}@  /|||||\  @    | | \__ \ | _|  | _|  | _| 
          {{bar}}@  \|/ \|/  @    |_| |___/ |___| |___| |___|
          {{bar}} @.       .@     
          {{bar}}  `Y@ @ @Y`      ISE Evaluation is Expired!
          {{bar}}
          {{bar}}{{ banner_text | default('', true) }}

    - name: Show Evaluation License Days Remaining as Bar
      when: ise_licensing_eval_days|int > 0
      vars:
        bar: "░  "
        bar_star: "★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★"
        bar_used: "__________________________________________________________________________________________"
        bar_arrw: "▶▶▶▶▶▶▶▶▶▶▶▶▶▶▶▶▶▶▶▶▶▶▶▶▶▶▶▶▶▶▶▶▶▶▶▶▶▶▶▶▶▶▶▶▶▶▶▶▶▶▶▶▶▶▶▶▶▶▶▶▶▶▶▶▶▶▶▶▶▶▶▶▶▶▶▶▶▶▶▶▶▶▶▶▶▶▶▶▶▶"
        bar_25:  "░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░"
        bar_75:  "▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓"
        bar_50:  "▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒"
        bar_100: "██████████████████████████████████████████████████████████████████████████████████████████"
      ansible.builtin.debug:
        msg: |
          {{bar}}                 
          {{bar}}                 
          {{bar}}      .          
          {{bar}}     /|\          _   ___   ___   ___   ___  
          {{bar}} @  /|||\  @     | | / __| | __| | __| | __|
          {{bar}}@  /|||||\  @    | | \__ \ | _|  | _|  | _| 
          {{bar}}@  \|/ \|/  @    |_| |___/ |___| |___| |___|
          {{bar}} @.       .@     
          {{bar}}  `Y@ @ @Y`      {{ ise_licensing_eval_days }}/90 Evaluation Days Remaining
          {{bar}}                 
          {{bar}}|{{ bar_75[0:ise_licensing_eval_days|int] }}{{ bar_25[0:(89 - ise_licensing_eval_days|int)] }}|
          {{bar}}|         |10       |20       |30       |40       |50       |60       |70       |80       |
          {{bar}}|123456789|123456789|123456789|123456789|123456789|123456789|123456789|123456789|123456789|
          {{bar}}                 

    - name: Show ISE Licensing Tiers & State
      when: ise_license_tier_state is defined 
        and ise_license_tier_state.status == 200
        and ise_license_tier_state.content | length > 0
      delegate_to: localhost
      vars:
        # maxw: "{{ maxw }}"
        # head: "{{ head }}"
        # hide: "{{ hide }}"
        rows: "{{ ise_license_tier_state.content }}"
        temp: "{{ lookup('template', 'list_of_dicts.j2') }}"
      ansible.builtin.debug:
        msg: "{{ temp }}"