---
#------------------------------------------------------------------------------
# ISE Eternal Evaluation (ISEEE) Password Reset Playbook
#
# 💡 Requires CLI option `--ask-pass` to prompt for SSH key password:
#
#   ansible-playbook iseee.password_reset.yaml --ask-pass
#
#------------------------------------------------------------------------------
- name: ISE Eternal Evaluation (ISEEE) - Password Reset
  hosts: iseee
  gather_facts: no
  vars:
  vars_files: vars/iseee.yaml
  roles:
    - ise_cli_password_reset
