---
- name: ISE Eternal Evaluation (ISEEE) - Certificates
  hosts: iseee
  gather_facts: no
  vars:
  vars_prompt:
  vars_files: vars/iseee.yaml
  roles:

    # Run these roles in case this is invoked after Provisioning
    - ise_login_await               # ISE SSH & HTTPS for CLI & GUI Login Page
    - ise_apis_enabled              # ISE ERS & OpenAPIs enabled

    - name: Not Implemented!
      role: banner
      vars:
        banner_name: warning
        banner_text: Not Implemented!

    # - ise_trusted_certificates_show_⚠
    # - ise_system_certificate_show_⚠

    # - ise_system_certificate_saved_⚠
    # - ise_trusted_certificates_saved_⚠

    # - ise_system_certificate_imported_⚠
    # - ise_trusted_certificates_imported_⚠
    # - ise_system_certificate_deleted_⚠

    # - name: ISEEE is Certificated!
    #   role: banner
    #   vars:
    #     banner_name: cisco_iseee_logo_small
    #     banner_text: ISEEE is Certificated!