---
- name: ISE Eternal Evaluation (ISEEE) - Patch & Hotpatch
  hosts: iseee
  gather_facts: no
  vars:
  vars_files: 
    - vars/ise_common.yaml
    - vars/iseee.yaml
  roles:

    # Run these roles in case this is invoked after Provisioning
    - ise_login_await     # ISE SSH & HTTPS for CLI & GUI Login Page
    - ise_apis_enabled    # ISE ERS & OpenAPIs enabled

    - ise_facts           # Gather ISE version, patch, & node state info
    - ise_facts_table     # Summarize ise_facts in a table
    - ise_repository      # Configure repository & set `ise_repository_name`
    - role: ise_node_patch      # Requires `ise_repository_name`, `ise_patch_filename`
      vars:
        ise_patch_filename: "{{ ise_patch_filenames[ise_semantic_version] }}"
    - ise_node_hotpatch   # Requires: ise_facts, ise_repository_name, ise_hotpatch_filenames

    - name: ISE is Patched!
      role: banner
      vars:
        banner_name: cisco_secure_ise_logo_small
        banner_text: ISE is Patched!
