---
#------------------------------------------------------------------------------
# ISEEE SSH Setup
#
# Use the `--ask-pass` command line opiton to  be prompted for the SSH key password:
# 
#  ansible-playbook iseee.yaml --ask-pass
#------------------------------------------------------------------------------
- name: ISE Eternal Evaluation (ISEEE) - ISEEE SSH Setup
  hosts: localhost # 💡 Use `localhost` for provisioning
  gather_facts: no
  vars:
  vars_files: vars/iseee.yaml
  roles:

    - ssh_key_local
    - aws_ec2_ssh_keypair_upload
