---
#------------------------------------------------------------------------------
# # ISE Eternal Evaluation (ISEEE) Backup Playbook
#------------------------------------------------------------------------------
- name: ISE Eternal Evaluation (ISEEE) - Backup
  hosts: iseee
  gather_facts: no
  vars:
    ise_repository_name: "{{ lookup('env','ISE_REPOSITORY_NAME') }}"
    ise_backup_encryption_key: "{{ lookup('env','ISE_BACKUP_ENCRYPTION_KEY') }}"
    ise_backup_name_prefix: "ISEEE_{{ DT_ISO8601 | strftime }}"
  vars_files: vars/iseee.yaml
  roles:
  
    - ise_repository_name # set `ise_repository_name`

    - ise_config_backup_now # Use the playbook vars above for this role

    # - role: ise_config_backup_now # Use the role vars
    #   vars:
    #     ise_repository_name: "{{ lookup('env','ISE_REPOSITORY_NAME') }}"
    #     ise_backup_encryption_key: "{{ lookup('env','ISE_BACKUP_ENCRYPTION_KEY') }}"
    #     ise_backup_name_prefix: ISEEE


    - name: ISEEE Backup Completed!
      role: banner
      vars:
        banner_name: cisco_iseee_logo_small
        # 💡 Use single-quotes (') for banner text; \'s in "'s are a special char delimiter!
        banner_line_2: ' ____                _              _  _   _         _ '
        banner_line_3: '| __ )   __ _   ___ | | __ ___   __| || | | | _ __  | |'
        banner_line_4: '|  _ \  / _` | / __|| |/ // _ \ / _` || | | || `_ \ | |'
        banner_line_5: '| |_) || (_| || (__ |   <|  __/| (_| || |_| || |_) ||_|'
        banner_line_6: '|____/  \__,_| \___||_|\_\\___| \__,_| \___/ | .__/ (_)'
        banner_line_7: '                                             |_|       '
        banner_text: ISEEE is Backed Up to {{ ise_repository_name }} ⮕ {{ ise_backup_filename }}
