---
#------------------------------------------------------------------------------
# Meraki Show Playbook
#
# Example commands:
#   ansible-playbook meraki.show.yaml 
#   ansible-playbook meraki.show.yaml --tags devices 
#
# Shows basic Cisco Meraki information
# - organization(s)
# - admin(s)
# - network(s)
# - device(s)
#
# There are no Ansible modules for many Meraki resources including:
# - cisco.meraki.adaptive_policy
# - cisco.meraki.group_policy
# - cisco.meraki.platform_*
# - ... and many more!
#
# Assumes MERAKI_KEY environment variable for API authentication:
#    export MERAKI_KEY='EXAMPLE+KEYc320e12ee407159487a4cabc41abb'
#------------------------------------------------------------------------------

- name: Show Meraki Admins, Organizations, Networks, and Devices
  hosts: localhost
  gather_facts: no
  roles:
    - meraki_show