---
#------------------------------------------------------------------------------
# ansible-playbook ping.yaml --limit ise -v
#------------------------------------------------------------------------------
- name: Test Ansible Ping
  hosts: all
  gather_facts: no # cannot gather facts until SSH Key copied!
  vars_files: 
  tasks:

    - name: Ping (SSH)
      ansible.builtin.ping:
      register: pong
