---
#------------------------------------------------------------------------------
# dCloud ISE Sandbox Lab Inventory
#------------------------------------------------------------------------------
# Verify your Anible inventory with
#   ansible-inventory --graph [ -i inventory/ise.yaml ]
#   ansible-inventory --list  [ -i inventory/ise.yaml ]
#   ansible-inventory --host {hostname}
#
# There are two default groups:
#   - all : contains every host
#   - ungrouped : contains all hosts not belonging to another group
#
# Variable precedence: all < parent group < child group < host
#
# For details on creating Ansible inventory files, see
# https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html
# For common patterns for targeting inventory hosts and groups:
# https://docs.ansible.com/ansible/latest/user_guide/intro_patterns.html
#------------------------------------------------------------------------------

all:
  vars: # global vars

    provider: dcloud # {dcloud|aws|azure|oci|...} hint for ISE superadmin
    project_name: dcloud_ise_sandbox
    dcloud_password_default: C1sco12345
    # dcloud_session_id: ________     # "{{ lookup('env', 'DCLOUD_SESSION_ID') }}"
    # dcloud_session_owner: ________  # "{{ lookup('env', 'DCLOUD_SESSION_OWNER') }}"

    # Find the public IPs in dCloud: MyHub > Sessions > View > Details >  Public IP Addresses
    # dcloud_ise_public_ip: 1.2.3.4
    # dcloud_wlc_public_ip: 1.2.3.4

  hosts:
    ise:
      ansible_host: 198.18.133.27

    ubuntu:
      ansible_host: 198.18.134.28
      ansible_become: true
      ansible_connection: ssh
      ansible_ssh_user: root
      # ansible_ssh_private_key_file: "{{ ssh_key_private_file }}"
      # ansible_ssh_password: C1sco12345     # 🛑 cannot use username:password without sshpass program
      apt_packages: # List of package names, specifiers (foo=1.0), or wildcards (foo* or foo=1.0*)
        - python3-pip # Package Installer for Python
        # - ansible   # installs ansible 2.9.6  8-( we want much later
        # - bcrypt    # generate SSH keys
        - curl
        # - docker
        # - docker-compose
        - git
        - tar
        - tree
        - vim
        - wget
        - net-tools # ifconfig
        # - ntp
        # - nmap
        # - wpasupplicant
        # - ca-certificates
      python_packages:
        - aiohttp
        - argparse
        - asyncio
        - requests
        - ansible # Python install gets the latest version
        # Ansible with AWS
        - boto3
        - botocore
        # Ansible with Cisco ISE
        - ciscoisesdk
        - jmespath

    # Windows Server 2016 with Active Directory, DHCP, DNS, NTP
    ad:
      ansible_host: 198.18.133.1
      ansible_user: dcloud\administrator
      ansible_password: C1sco12345

    # Windows Exchange Mail Server
    exchange:
      ansible_host: 198.18.133.2
      ansible_user: dcloud\administrator
      ansible_password: C1sco12345

    # Cisco Catalyst 9800CL
    wlc:
      ansible_host: 198.19.11.10
      public_ip: 128.107.222.101 # ⭐ Change Me!
      ansible_user: "{{ dcloud_session_owner }}"
      ansible_password: "{{ dcloud_session_id }}"

    # Windows 10 Bastion/Jump host
    workstation:
      ansible_host: 198.18.133.36
      ansible_user: administrator
      ansible_password: C1sco12345

    # Cisco 881 dCloud Router
    dcloud_router:
      ansible_host: 10.80.60.145
      ansible_user: admin
      ansible_password: C1sco12345

  children: # define groups from the hosts above
    ise: # all of the ISE nodes
      hosts:
        ise:
      vars:
        ansible_connection: ansible.netcommon.network_cli
        ansible_network_os: cisco.ios.ios
        # ⭐ ISE SSH username is `iseadmin` for ISE 3.2+ cloud instances!
        ansible_ssh_user: "{{ lookup('env','ISE_SSH_USERNAME') }}"
        # ⭐ Un/Comment the SSH password or key - whichever you use!
        ansible_ssh_password: "{{ lookup('env','ISE_SSH_PASSWORD') }}"
        # ansible_ssh_private_key_file: ~/.ssh/dcloud_ise_sandbox

        ise_username: "{{ lookup('env','ISE_USERNAME') }}"
        ise_password: "{{ lookup('env','ISE_PASSWORD') }}"
        # ise_username: admin # ISE superadmin name: admin @ ISE <= 3.1 | iseadmin @ ISE >= 3.2 in cloud
        # ise_password: ISEisC00L

        # ISE Backup & Restore
        ise_repository_name: "{{ lookup('env','ISE_REPOSITORY_NAME') }}"
        ise_backup_encryption_key: "{{ lookup('env','ISE_BACKUP_ENCRYPTION_KEY') }}"
        ise_backup_name_prefix: dCloud # "NOW" by default
        # ise_restore_filename: ISEEE-CFG10-230803-0107.tar.gpg   # restore this configuration file to ISEEE

        # 
        # You may use host vars or group_vars for patch definitions, too
        #
        # ise_repository_name: "{{ lookup('env','ISE_REPOSITORY_NAME') }}"
        # ise_patch_filename: ise-patchbundle-3.1.0.518-Patch3-22042809.SPA.x86_64.tar.gz
        # ise_patch_filename: ise-patchbundle-3.1.0.518-Patch4-22091704.SPA.x86_64.tar.gz
        # ise_patch_filename: ise-patchbundle-3.1.0.518-Patch7-23052004.SPA.x86_64.tar.gz
        # ise_patch_filename: ise-patchbundle-3.2.0.542-Patch1-23011406.SPA.x86_64.tar.gz
        # ise_patch_filename: ise-patchbundle-3.2.0.542-Patch2-23050309.SPA.x86_64.tar.gz
        # ise_patch_filename: ise-patchbundle-3.2.0.542-Patch3-23071904.SPA.x86_64.tar.gz
        # ise_hotpatch_filenames:
        #   - ise-hotpatchbundle-3.2.0.542-Patch2-23050309.SPA.x86_64.tar.gz

    linux: # all of the Linux workstations
      hosts:
        ubuntu:

    windows: # all of the Windows workstations
      hosts:
        ad:
        workstation:
        exchange:
      vars:
        ansible_port: 5985
        ansible_connection: winrm
        ansible_winrm_transport: ntlm
        ansible_winrm_server_cert_validation: ignore
