---
#------------------------------------------------------------------------------
# dCloud ISE Sandbox Lab Inventory
#------------------------------------------------------------------------------
# Verify your Anible inventory with
#   ansible-inventory --graph [ -i inventory/ise.yaml ]
#   ansible-inventory --list  [ -i inventory/ise.yaml ]
#   ansible-inventory --host {hostname}
#
# There are two default groups:
#   - all : contains every host
#   - ungrouped : contains all hosts not belonging to another group
#
# Variable precedence: all < parent group < child group < host
#
# For details on creating Ansible inventory files, see
# https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html
# For common patterns for targeting inventory hosts and groups:
# https://docs.ansible.com/ansible/latest/user_guide/intro_patterns.html
#------------------------------------------------------------------------------
# ðŸ›‘ Inventory files are static - variables and filters are not evaluated!
all:
  vars: # global vars
    project_name: dcloud_ise_sandbox # tag all VPCs and resources
    dcloud_password_default: C1sco12345

  hosts:
    ise:
      ansible_host: 198.18.133.27
      vars:
        ansible_connection: ansible.netcommon.network_cli
        ansible_network_os: cisco.ios.ios
        ansible_ssh_user: admin
        ansible_ssh_password: C1sco12345
        # ansible_ssh_private_key_file: ~/.ssh/dcloud_ise_sandbox

    ubuntu:
      ansible_host: 198.18.134.28
      ansible_become: true
      ansible_connection: ssh
      ansible_ssh_user: root
      # ansible_ssh_private_key_file: "{{ ssh_key_private_file }}"
      ansible_ssh_password: C1sco12345     # ðŸ›‘ cannot use username:password without sshpass program
      apt_packages: # List of package names, specifiers (foo=1.0), or wildcards (foo* or foo=1.0*)
        - ansible   # installs ansible 2.9.6  8-( we want much later
        - bcrypt    # generate SSH keys
        - curl
        - git
        - net-tools # ifconfig
        - pipenv
        - python3
        - python3-pip # Package Installer for Python
        - rsync
        - ssh
        - sshpass
        - tar
        - tree
        - vim
        - wget
        # - ca-certificates
        # - docker
        # - docker-compose
        # - nmap
        # - ntp
        # - wpasupplicant
      python_packages:
        - aiohttp
        - argparse
        - asyncio
        - bcrypt      # create SSH keys and passwords
        - ciscoisesdk # Ansible cisco.ise
        - jinja2
        - jmespath
        - paramiko
        - passlib     # create Linux users
        - requests
        - urllib3
        - ansible # Python install gets the latest version
        # Ansible with AWS
        - boto3
        - botocore

    # Windows Server 2016 with Active Directory, DHCP, DNS, NTP
    ad:
      ansible_host: 198.18.133.1
      ansible_user: dcloud\administrator
      ansible_password: C1sco12345

    # Windows Exchange Mail Server
    exchange:
      ansible_host: 198.18.133.2
      ansible_user: dcloud\administrator
      ansible_password: C1sco12345

    # Cisco Catalyst 9800CL
    wlc:
      ansible_host: 198.19.11.10
      public_ip: 128.107.222.101 # â­ Change Me!
      ansible_user: "{{ dcloud_session_owner }}"
      ansible_password: "{{ dcloud_session_id }}"

    # Windows 10 Bastion/Jump host
    workstation:
      ansible_host: 198.18.133.36
      ansible_user: administrator
      ansible_password: C1sco12345

    # Cisco 881 dCloud Router
    dcloud_router:
      ansible_host: 10.80.60.145
      ansible_user: admin
      ansible_password: C1sco12345

  children: # define groups from the hosts above
    ise: # all of the ISE nodes
      hosts:
        ise:

    linux: # all of the Linux workstations
      hosts:
        ubuntu:

    windows: # all of the Windows workstations
      hosts:
        ad:
        workstation:
        exchange:
      vars:
        ansible_port: 5985
        ansible_connection: winrm
        ansible_winrm_transport: ntlm
        ansible_winrm_server_cert_validation: ignore

    wlcs:
      hosts:
        wlc:

    routers:
      hosts:
        dcloud_router: