---
#------------------------------------------------------------------------------
# DevNet Always-On ISE Sandbox node for API Testing.
#   https://devnetsandboxise.cisco.com
# The DevNet Always-On ISE Sandbox node is Read-Only.
# 🛑 Ping and SSH are blocked. Only HTTPS (port 443) is allowed!
#------------------------------------------------------------------------------
# Verify your Anible inventory with
#   ansible-inventory --graph [ -i inventory/ise.yaml ]
#   ansible-inventory --list  [ -i inventory/ise.yaml ]
#   ansible-inventory --host {hostname}
#
# There are two default groups:
#   - all : contains every host
#   - ungrouped : contains all hosts not belonging to another group
#
# Variable precedence: all < parent group < child group < host
#
# For details on creating Ansible inventory files, see
# https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html
# For common patterns for targeting inventory hosts and groups:
# https://docs.ansible.com/ansible/latest/user_guide/intro_patterns.html
#------------------------------------------------------------------------------

all:
  vars: # global vars
  children: # define groups from the hosts above
    ise: # all of the ISE nodes
      hosts:
        # ▼ Un/comment and edit to match ISE node's names and IP addresses! ▼
        devnetsandboxise:
          ansible_host: devnetsandboxise.cisco.com
          # ansible_host: 172.64.36.1
      # Define group vars here or in `inventory/group_vars/ise.yaml`
      vars:
        project_name: DevNetSandboxISE # tag all VPCs and resources

        # 💡 DevNetSandboxISE does not use SSH keys
        # ssh_keypair_directory: ~/.ssh
        # ssh_keypair_name: "{{ project_name }}"

        ansible_connection: ansible.netcommon.network_cli
        ansible_network_os: cisco.ios.ios
        ansible_ssh_user: "{{ lookup('env','ISE_SSH_USERNAME') }}" # ISE 3.2+ cloud instances use `iseadmin`
        # 💡 Un/Comment the SSH password or key - whichever you use!
        ansible_ssh_password: "{{ lookup('env','ISE_SSH_PASSWORD') }}" # appliances & VMs
        # ansible_ssh_private_key_file: "{{ ssh_keypair_directory }}/{{ ssh_keypair_name }}" # 💡 No SSH keys

        ise_username: "{{ lookup('env','ISE_USERNAME') }}" # 💡 `iseadmin` for ISE 3.2+ cloud instances 
        ise_password: "{{ lookup('env','ISE_PASSWORD') }}"

        # Used in roles/ise_network_devices
        ise_radius_secret: "{{ lookup('env','ISE_RADIUS_SECRET') }}"
        ise_tacacs_secret: "{{ lookup('env','ISE_TACACS_SECRET') }}"
