---
#------------------------------------------------------------------------------
# DevNet Always-On ISE Sandbox node for API Testing.
#   https://devnetsandboxise.cisco.com
# The DevNet Always-On ISE Sandbox node is Read-Only.
# 🛑 Ping and SSH are blocked. Only HTTPS (port 443) is allowed!
#------------------------------------------------------------------------------
# Verify your Anible inventory with
#   ansible-inventory --graph [ -i inventory/ise.yaml ]
#   ansible-inventory --list  [ -i inventory/ise.yaml ]
#   ansible-inventory --host {hostname}
#
# There are two default groups:
#   - all : contains every host
#   - ungrouped : contains all hosts not belonging to another group
#
# Variable precedence: all < parent group < child group < host
#
# For details on creating Ansible inventory files, see
# https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html
# For common patterns for targeting inventory hosts and groups:
# https://docs.ansible.com/ansible/latest/user_guide/intro_patterns.html
#------------------------------------------------------------------------------
# 🛑 Variables are not evaluated in inventory files!
all:
  vars: # global vars
  hosts:
    devnetsandboxise:
      ansible_host: devnetsandboxise.cisco.com
      ansible_connection: ansible.netcommon.network_cli
      ansible_network_os: cisco.ios.ios
      ansible_ssh_user: admin
      # ansible_ssh_password: _____
      # ansible_ssh_private_key_file: /path/to/private/key
      # ansible_host: 1.2.3.4

ise_deployment:
  children:
    devnetsandboxise:
      vars: