---
# -----------------------------------------------------------------------------
# Verify your Anible inventory with
#   ansible-inventory -i inventory --graph
#   ansible-inventory -i inventory --host <hostname>
#   ansible-inventory -i inventory --list
#
# There are two default groups:
#   - all : contains every host
#   - ungrouped : contains all hosts not belonging to another group
#
# Variable precedence: all < parent group < child group < host
#
# For details on creating Ansible inventory files, see
# https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html
# For common patterns for targeting inventory hosts and groups:
# https://docs.ansible.com/ansible/latest/user_guide/intro_patterns.html
# -----------------------------------------------------------------------------

all:
  vars: # global vars
  children: # define groups from the hosts above
    ise: # all of the ISE nodes
      hosts:
        # ▼ Un/comment and edit to match ISE node's names and IP addresses! ▼
        ise:
          ansible_host: 198.18.133.27
        # ise-ppan: 
        #   ansible_host: 10.1.100.21
        # ise-span: 
        #   ansible_host: 10.1.100.22
        # ise-psn1: 
        #   ansible_host: 10.1.100.23
        # ise-psn2: 
        #   ansible_host: 10.1.100.24
        # ise-aws:
        #   ansible_host: 172.31.1.21
        # ise-azure:
        #   ansible_host: 172.31.1.21
        # ise-hyperv:
        #   ansible_host: 10.1.100.23
        # ise-kvm:
        #   ansible_host: 10.1.100.24
        # ise-nutanix:
        #   ansible_host: 10.1.100.25
        # ise-oci:
        #   ansible_host: 172.31.1.21

      vars:
        ssh_keypair_directory: ~/.ssh
        ssh_keypair_name: "{{ project_name }}"

        ansible_connection: ansible.netcommon.network_cli
        ansible_network_os: cisco.ios.ios
        ansible_ssh_user: "{{ lookup('env','ISE_SSH_USERNAME') }}" # ISE 3.2+ cloud instances use `iseadmin`
        # 💡 Un/Comment the SSH password or key - whichever you use!
        ansible_ssh_password: "{{ lookup('env','ISE_SSH_PASSWORD') }}" # appliances & VMs
        # ansible_ssh_private_key_file: "{{ ssh_keypair_directory }}/{{ ssh_keypair_name }}" # cloud instances

        ise_username: "{{ lookup('env','ISE_USERNAME') }}" # 💡 `iseadmin` for ISE 3.2+ cloud instances 
        ise_password: "{{ lookup('env','ISE_PASSWORD') }}"
