---
# tasks file for roles/to_yaml_file

- name: To YAML File | ./{{ resource }}.yaml
  when:
    - resource is defined
    - resources is defined
    - resources | count > 0
  delegate_to: localhost
  ansible.builtin.template:
    src: templates/resource_template.j2
    dest: "./{{ resource }}.yaml"
    mode: "0644"
