---
# tasks file for roles/ise_internal_users

- name: ISE Internal Users
  when:
    - internal_users is defined
    - internal_users | count > 0
  loop: "{{ internal_users }}"
  cisco.ise.internal_user:
    ise_hostname: "{{ ansible_host }}"
    ise_username: "{{ ise_username | default( omit ) }}"
    ise_password: "{{ ise_password | default( omit ) }}"
    state: "{{ item.state | default('present') }}"
    name:  "{{ item.username }}"
    password: "{{ item.password | default( omit ) }}"
    description: "{{ item.description |  default( omit ) }}"
    enabled: "{{ item.enabled | default(True) }}"
    expiryDateEnabled: "{{ item.expiryDateEnabled | default(False) }}"
    # ▼▼▼ optional attributes ▼▼▼
    changePassword: "{{ item.changePassword | default(False) }}"
    passwordIDStore: "{{ item.idStore | default('Internal Users') }}"
    # identityGroups: a1740510-8c01-11e6-996c-525400b48521
    identityGroups: "{{ item.identityGroups | default(IDENTITY_GROUP_DEFAULT) }}"

    # customAttributes:
    #   Created:
    #   Expired:   register: create_users

  register: internal_users_results
  no_log: yes
