---
# tasks file for roles/aws_ec2_instance_state


- name: Get all EC2 Instances | project:{{ project }} | {{ states }}
  delegate_to: localhost
  community.aws.ec2_instance_info: # get all by default
    filters:
      "tag:project": "{{ project | default(omit) }}"
      instance-state-name: "{{ states | default(omit) }}" # on or more: [present, running, started, stopped, rebooted, restarted, terminated, absent]
  register: ec2

- name: Show EC2 Instances | project:{{ project }} | {{ states }}
  delegate_to: localhost
  when:
    - ec2 is defined
    - ec2.instances is defined
    - ec2.instances | count > 0
  vars:
    # hide: ['security_groups','tags']
    head:
      [
        "key_name",
        "state",
        "public_ip_address",
        "private_ip_address",
        "instance_type",
        "instance_id",
        "image_id",
      ]
    hide: []
    maxw: 40
    rows: "{{ ec2.instances }}"
    temp: "{{ lookup('template', './templates/list_of_dicts.j2') }}"
  ansible.builtin.debug:
    msg: "{{ temp }}"
  tags: [ec2, instances]
