---
# tasks file for roles/to_yaml

- name: To YAML | {{ resource }}
  delegate_to: localhost
  # ansible.builtin.shell: "echo '{{ lookup('vars', resource, default='') | to_nice_yaml(indent=2) }}' > /dev/tty"
  ansible.builtin.debug:
    msg: |
      {{ resource }} : {{ lookup('vars', resource, default='UNDEFINED') }}
  ignore_errors: true
