---
# tasks file for roles/ise_login_await

- name: Wait for ISE SSH ∆ ∆ ∆ (➚{{ wait_timeout }}s)
  delegate_to: localhost
  ansible.builtin.wait_for:
    host: "{{ ansible_host }}"
    port: 22
    state: "{{ wait_state }}"
    delay: "{{ wait_delay }}"
    sleep: "{{ wait_sleep }}"
    timeout: "{{ wait_timeout }}"

- name: Wait for ISE HTTPS ∆ ∆ ∆ (➚{{ wait_timeout }}s)
  delegate_to: localhost
  ansible.builtin.wait_for:
    host: "{{ ansible_host }}"
    port: 443
    state: "{{ wait_state }}"
    delay: "{{ wait_delay }}"
    sleep: "{{ wait_sleep }}"
    timeout: "{{ wait_timeout }}"

- name: Wait for ISE GUI Login (➚{{ wait_retries * (wait_delay + wait_uri_timeout) }}s)
  delegate_to: localhost
  ansible.builtin.uri:
    url: https://{{ ansible_host }}/admin/login.jsp
    method: GET
    follow_redirects: safe
    timeout: "{{ wait_uri_timeout }}"
    validate_certs: "{{ wait_validate_certs }}"
    return_content: no
  register: info
  until: info.status == 200
  retries: "{{ wait_retries }}"
  delay: "{{ wait_sleep }}" # wait between checks
