---
# defaults file for roles/ise_show

DT_TIMESTAMP: "%Y%m%dT%H%M%S%z" # YYYYMMDDTHHMMSS±nnnn
IGNORE_ERRORS: no

ise_show_list: yes
ise_show_table: yes
ise_show_save: yes

project: "{{ lookup('env','PROJECT') | default('project') }}"

# ./{{ files }}
dir_ansible_files: ./files

# ./{{ files }}/{{ project }}/
dir_project_files: "{{ dir_ansible_files }}/{{ project }}"

# ./{{ files }}/{{ project }}/ise_show/
dir_ise_show: "{{ dir_project_files }}/ise_show"

# ./{{ files }}/{{ project }}/ise_show/
dir_ise_show_configs:       "{{ dir_ise_show }}/configs"

# ./{{ files }}/{{ project }}/ise/certificates/
dir_ise_show_certs:    "{{ dir_ise_show }}/certificates"
dir_ise_show_certs_system:  "{{ dir_ise_show_certs }}/system"
dir_ise_show_certs_trusted: "{{ dir_ise_show_certs }}/trusted"
