---
# defaults file for roles/ise_show

# export_configs: yes

# ./{{ files }}
dir_ansible_files: ./files

# ./{{ files }}/{{ project }}/
project_name: default
dir_project_files: "{{ dir_ansible_files }}/{{ project_name }}"

# ./{{ files }}/{{ project }}/ise/
dir_ise: "{{ dir_project_files }}/ise"

# ./{{ files }}/{{ project }}/ise/configs/
dir_ise_configs:       "{{ dir_ise }}/configs"

# ./{{ files }}/{{ project }}/ise/certificates/
dir_ise_certs:         "{{ dir_ise }}/certificates"
dir_ise_certs_system:  "{{ dir_ise }}/certificates/system"
dir_ise_certs_trusted: "{{ dir_ise }}/certificates/trusted"
