---
# tasks file for roles/to_json

- name: To JSON ({{ var }})
  delegate_to: localhost
  # ansible.builtin.shell: "echo '{{ lookup('vars', var, default='') | to_nice_json(indent=2) }}' > /dev/tty"
  ansible.builtin.debug:
    msg: "{{ lookup('vars', var, default='') | to_nice_json(indent=2) }}"
