---
# tasks file for roles/to_json

- name: To JSON ({{ resource }})
  delegate_to: localhost
  # ansible.builtin.shell: "echo '{{ lookup('vars', resource, default='') | to_nice_json(indent=2) }}' > /dev/tty"
  ansible.builtin.debug:
    msg: |
      { "{{ resource }}": {{ lookup('vars', resource, default='UNDEFINED') | to_nice_json(indent=2) }}
