---
# tasks file for roles/ise_endpoint_groups

- name: ISE Endpoint Groups
  delegate_to: localhost
  when:
    - endpointgroup is defined
    - endpointgroup | count > 0
  loop: "{{ endpointgroup }}"
  cisco.ise.endpoint_group:
    ise_hostname: "{{ ansible_host }}"
    ise_username: "{{ ise_username | default( omit ) }}"
    ise_password: "{{ ise_password | default( omit ) }}"
    state: "{{ item.state | default('present') }}"
    name: "{{ item.name }}"
    description: "{{ item.description | default( omit ) }}"
    systemDefined: "{{ item.systemDefined | default('false') }}"
  ignore_errors: true
  register: endpoint_groups_results
  tags: [endpointgroup, endpointgroups, endpoint_group, endpointgroup]
