---
# tasks file for roles/ise_cli_dns_service_cache_enabled

#------------------------------------------------------------------------------
# ⚠ DNS Caching is *disabled* by default.
# ⚠ Using a DNS name for syslog server(s) causes a lookup for every log!
# ⚠ Without DNS caching, there can be major latency in ISE!
#------------------------------------------------------------------------------
# ise/admin#configure terminal
# Entering configuration mode terminal
# ise/admin(config)#service cache enable hosts ttl 300
# Successfully enabled DNS cache
#------------------------------------------------------------------------------

# ??? ToDo: Don't know why I get this message with SSH
# fatal: [iseee]: FAILED! => changed=false
#   msg: Connection type ssh is not valid for this module

- name: ISE CLI | Enable DNS Caching | {{ inventory_hostname }}
  vars:
    ansible_connection: ansible.netcommon.network_cli
    ansible_network_os: cisco.ios.ios
  cisco.ios.ios_config:
    lines: service cache enable hosts ttl 300
  register: cli_output
  failed_when: cli_output.failed
  ignore_errors: true


#----------------------------------------------------------------------------
# Example cli_output:
#
# cli_output:   # success
#   banners: {}
#   changed: true
#   commands:
#   - service cache enable hosts ttl 300
#   failed: false
#   updates:
#   - service cache enable hosts ttl 300
#   warnings:
#   - To ensure idempotency and correct diff the input configuration lines
#     should be similar to how they appear if present in the running
#     configuration on device
#
# cli_output:   # success - no change
#   changed: false
#   failed: false
#----------------------------------------------------------------------------

- name: Exit | {{ inventory_hostname }}
  ansible.netcommon.cli_command:
    command: "exit"
  ignore_errors: true
