---
# List any role dependencies, one per line.
dependencies:
  - ise_facts

galaxy_info:
  author: Thomas Howard, thomas@cisco.com
  description: Apply the specified Patch file to an ISE node
  company: Cisco Systems

  # If the issue tracker for your role is not on github, uncomment the
  # next line and provide a value
  # issue_tracker_url: http://example.com/issue/tracker

  license: MIT
  min_ansible_version: 2.13

  # If this a Container Enabled role, provide the minimum Ansible Container version.
  # min_ansible_container_version:

  #
  # Provide a list of supported platforms, and for each platform a list of versions.
  # If you don't wish to enumerate all versions for a particular platform, use 'all'.
  # To view available platforms and versions (or releases), visit:
  # https://galaxy.ansible.com/api/v1/platforms/
  #
  # platforms:
  # - name: Fedora
  #   versions:
  #   - all
  #   - 25
  # - name: SomePlatform
  #   versions:
  #   - all
  #   - 1.0
  #   - 7
  #   - 99.99

  # List tags (a single word of alphanumeric characters) for your role here.
  # Maximum 20 tags per role.
  galaxy_tags:
  - cisco
  - ise
  - identityservicesengine
