---
# tasks file for roles/apt_update_upgrade

- name: Update apt Repo and Cache
  become: yes
  ansible.builtin.apt:
    cache_valid_time: "{{ cache_valid_time }}"
    force_apt_get: yes
    update_cache: yes
  register: apt_update_cache

- name: Get List of Available Package Updates
  become: yes
  ansible.builtin.command: apt list --upgradable
  register: apt_updates

- name: Show Available Package Updates
  delegate_to: localhost
  ansible.builtin.debug:
    msg: "{{ apt_updates.stdout_lines }}"

#
# Equivalent of `sudo apt update && sudo apt -y upgrade`
#

- name: apt Update and Upgrade Packages
  become: yes
  ansible.builtin.apt:
    upgrade: yes
  register: upgrade_status

