---
# tasks file for roles/aws_security_groups
- name: sg_allow_all Security Group
  amazon.aws.ec2_group:
    vpc_id: "{{ vpc.vpc.id }}"
    # region: "{{ region }}" # not needed with vpc_id
    name: sg_allow_all
    description: Public Access Security Group
    rules:
      - rule_desc: Allow All
        proto: all
        cidr_ip: 0.0.0.0/0 # any
    rules_egress:
      - rule_desc: Allow All
        proto: all
        cidr_ip: 0.0.0.0/0 # any
    tags:
      Name: sg_allow_all
      owner: "{{ owner }}"
      project: "{{ project | default(omit) }}"
      started: "{{ '%Y%m%dT%H%M%S-%Z' | strftime }}"
  register: sg_allow_all

- name: Create Security Group `sg_ise_pan`
  amazon.aws.ec2_group:
    name: sg_ise_pan
    description: ISE PAN Node
    vpc_id: "{{ vpc.vpc.id }}"
    # region: "{{ region }}" # not needed with vpc_id
    rules:
      - proto: icmp
        ports: -1 # all ICMP ports
        cidr_ip: 0.0.0.0/0 # any
        rule_desc: ICMP
      - proto: tcp
        ports: 22
        cidr_ip: 0.0.0.0/0 # any
        rule_desc: SSH
      - proto: tcp
        ports: 80
        cidr_ip: 0.0.0.0/0 # any
        rule_desc: HTTP
      - proto: tcp
        ports: 443
        cidr_ip: 0.0.0.0/0 # any
        rule_desc: HTTPS
    rules_egress:
      - proto: all
        cidr_ip: 0.0.0.0/0 # any
    tags:
      Name: sg_ise_pan
      owner: "{{ owner | default(omit) }}"
      project: "{{ project | default(omit) }}"
      started: "{{ '%Y%m%dT%H%M%S-%Z' | strftime }}"
  register: sg_ise_pan

- name: Create Security Group `sg_ise_psn`
  amazon.aws.ec2_group:
    vpc_id: "{{ vpc.vpc.id }}"
    # region: "{{ region }}" # not needed with vpc_id
    state: present
    name: sg_ise_psn
    description: sg_ise_psn
    rules:
      - rule_desc: ICMP
        proto: icmp
        ports: -1 # all ICMP ports
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        ports: 22
        cidr_ip: 0.0.0.0/0 # any
        rule_desc: SSH
      - proto: tcp
        ports: 49
        cidr_ip: 0.0.0.0/0 # any
        rule_desc: TACACS+
      # 
      # - proto: udp
      #   ports: 53
      #   cidr_ip: 0.0.0.0/0 # any
      #   rule_desc: DNS
      # - proto: tcp
      #   ports: 67-68
      #   cidr_ip: 0.0.0.0/0 # any
      #   rule_desc: DHCP
      - proto: tcp
        ports: 80
        cidr_ip: 0.0.0.0/0 # any
        rule_desc: HTTP
      - proto: udp
        ports: 161-162
        cidr_ip: 0.0.0.0/0 # any
        rule_desc: SNMP + Traps
      - proto: tcp
        ports: 443
        cidr_ip: 0.0.0.0/0 # any
        rule_desc: HTTPS
      - proto: udp
        ports: 500
        cidr_ip: 0.0.0.0/0 # any
        rule_desc: IPsec
      # - proto: udp
      #   ports: 1645-1646
      #   cidr_ip: 0.0.0.0/0 # any
      #   rule_desc: RADIUS Auth & Acct (Old!)
      - proto: udp
        ports: 1812-1813
        cidr_ip: 0.0.0.0/0 # any
        rule_desc: RADIUS Auth & Acct
      # - proto: udp
      #   ports: 1700
      #   cidr_ip: 0.0.0.0/0 # any
      #   rule_desc: RADIUS CoA (old)
      - proto: udp
        ports: 3799
        cidr_ip: 0.0.0.0/0 # any
        rule_desc: RADIUS CoA
      - proto: tcp
        ports: 2484
        cidr_ip: 0.0.0.0/0 # any
        rule_desc: Data Connect
      - proto: udp
        ports: 2083
        cidr_ip: 0.0.0.0/0 # any
        rule_desc: DTLS
      - proto: tcp
        ports: 2560
        cidr_ip: 0.0.0.0/0 # any
        rule_desc: OCSP
      - proto: tcp
        ports: 1521
        cidr_ip: 0.0.0.0/0 # any
        rule_desc: ISE Inter-Node Oracle DB
      - proto: tcp
        ports: 6379
        cidr_ip: 0.0.0.0/0 # any
        rule_desc: Profiler Endpoint Ownership Synchronization & Replication
      - proto: tcp
        ports: 8443
        cidr_ip: 0.0.0.0/0 # any
        rule_desc: Guest & Sponsor Portals
      - proto: tcp
        ports: 8671
        cidr_ip: 0.0.0.0/0 # any
        rule_desc: ISE Messaging Service SSL
      - proto: tcp
        ports: 8905
        cidr_ip: 0.0.0.0/0 # any
        rule_desc: Posture
      - proto: tcp
        ports: 9300
        cidr_ip: 0.0.0.0/0 # any
        rule_desc: ElasticSearch Replication PPAN-SPAN
      - proto: tcp
        ports: 12001
        cidr_ip: 0.0.0.0/0 # any
        rule_desc: ISE Inter-Node Data Synchronization & Replication (JGroups)
      - proto: tcp
        ports: 15672
        cidr_ip: 0.0.0.0/0 # any
        rule_desc: ISE Inter-Node internal communication
      - proto: tcp
        ports: 8910
        cidr_ip: 0.0.0.0/0 # any
        rule_desc: ISE CA PKI
      # - proto: tcp
      #   ports: 9060
      #   cidr_ip: 0.0.0.0/0 # any
      #   rule_desc: ERS API before API Gateway
      - proto: tcp
        ports: 9090
        cidr_ip: 0.0.0.0/0 # any
        rule_desc: pxGrid
      - proto: udp
        ports: 9996
        cidr_ip: 0.0.0.0/0 # any
        rule_desc: NetFlow
      - proto: udp
        ports: 6514
        cidr_ip: 0.0.0.0/0 # any
        rule_desc: Secure Syslog to MNT
      - proto: udp
        ports: 20514
        cidr_ip: 0.0.0.0/0 # any
        rule_desc: Syslog to MNT
      - proto: tcp
        ports: 64999
        cidr_ip: 0.0.0.0/0 # any
        rule_desc: SXP
    # rules_egress: # If none are supplied, a default all-out rule is assumed
    #   - proto: any
    #     cidr_ip: 0.0.0.0/0    # any
    #     rule_desc: Any
    tags:
      Name: sg_ise_psn
      owner: "{{ owner | default(omit) }}"
      project: "{{ project | default(omit) }}"
      started: "{{ '%Y%m%dT%H%M%S-%Z' | strftime }}"
  register: sg_ise_psn
