---
# tasks file for roles/ise_node_ppan
#------------------------------------------------------------------------------
# No assertions for required variables
# By default, this playbook will not FAIL - only assert problems and continue.
# There are 4 possible scenarios:
# - ISE node has non-PAN roles/services; demote to Standalone
# - promote Secondary Policy Administration Node (SPAN) to PPAN
# - promote Standalone node to PPAN
# - ISE node is already a Primary Policy Administration Node (PPAN)
#------------------------------------------------------------------------------

#------------------------------------------------------------------------------
#   roles:    # Default: ['Standalone']. Use [] (no roles) for dedicated PSN
#   - Standalone
#   - PrimaryAdmin
#   - PrimaryMonitoring
#   - SecondaryAdmin
#   - SecondaryMonitoring
#   - PrimaryDedicatedMonitoring
#   - SecondaryDedicatedMonitoring
#   services: # Default: ['Session','Profiler']. Use [] for dedicated PAN/MNT (no services)
#   - DeviceAdmin
#   - Profiler
#   - Session
#   - pxGrid
#   - pxGridCloud
#   - PassiveIdentity
#   - SXP
#   - TC-NAC
#------------------------------------------------------------------------------

- name: Get ISE Deployment Info | {{ inventory_hostname }} ({{ ansible_host }})
  cisco.ise.node_deployment_info:
    ise_hostname: "{{ ansible_host }}"
    ise_username: "{{ ise_username | default( omit ) }}"
    ise_password: "{{ ise_password | default( omit ) }}"
    hostname: "{{ inventory_hostname }}"
  register: ise_node_info

  # Example:
  # ```
  # ise_response:
  #   fqdn: ise.securitydemo.net
  #   hostname: ise
  #   ipAddress: 198.18.133.27
  #   nodeStatus: Connected
  #   roles:
  #   - PrimaryAdmin
  #   - PrimaryMonitoring
  #   services:
  #   - Session
  #   - Profiler
  # ```

# - name: ISE Node Info | '{{ inventory_hostname }}' ({{ ansible_host }})
#   ansible.builtin.set_fact:
#     # ise_node_info: "{{ ise_node_info.ise_response |flatten }}"
#     ise_node_info:
#       roles: "{{ ise_node_info.ise_response.roles }}"
#       services: "{{ ise_node_info.ise_response.services }}"

- name: Assert ISE Node Standalone
  ansible.builtin.assert:
    that: "'Standalone' in ise_node_info.ise_response.roles"
  ignore_errors: yes
  register: assert_standalone

- name: Assert ISE Node PrimaryAdmin
  ansible.builtin.assert:
    that: "'PrimaryAdmin' in ise_node_info.ise_response.roles"
  ignore_errors: yes
  register: assert_ppan

- name: Assert ISE Node SecondaryAdmin
  ansible.builtin.assert:
    that: "'SecondaryAdmin' in ise_node_info.ise_response.roles"
  ignore_errors: yes
  register: assert_span

- name: Assert ISE Node Not Standalone/PPAN/SPAN
  when: 
    - assert_standalone.failed
    - assert_ppan.failed
    - assert_span.failed
  ignore_errors: yes
  ansible.builtin.debug:
    msg: "{{ inventory_hostname }} ({{ ansible_host }}) is something else: {{ ise_node_info.ise_response.roles }}"

- name: ISE Node Tagged for PrimaryAdmin
  when: "'PrimaryAdmin' in ise_node_info.ise_response.roles"
  ansible.builtin.debug:
    msg: "{{ inventory_hostname }} ({{ ansible_host }}) is tagged for PrimaryAdmin!"


- name: Promote ISE Node SecondaryAdmin ⮕ PrimaryAdmin (⧖45s|➚60s) | {{ inventory_hostname }} ({{ ansible_host }})
  when: "'SecondaryAdmin' in ise_node_info.ise_response.roles"
  # ansible.builtin.debug:
  #   msg: "{{ inventory_hostname }} ({{ ansible_host }}) is SecondaryAdmin!"
  cisco.ise.node_secondary_to_primary:
    ise_hostname: "{{ ansible_host }}"
    ise_username: "{{ ise_username | default( oamit ) }}"
    ise_password: "{{ ise_password | default( omit ) }}"
    hostname: "{{ inventory_hostname }}" # must use hostname, not IP (ansible_host)
  register: ise_node_primary

# POST /api/v1/deployment/primary
# Promotes the node on which the API is invoked to the primary ISE PAN.
# ⏲ Approximate execution time ~60 seconds!
# ↻ No restart when changing from Standalone to Primary PAN
- name: ISE Node Standalone ⮕ PrimaryAdmin (⧖45s|➚60s) | {{ inventory_hostname }} ({{ ansible_host }})
  when: "'Standalone' in ise_node_info.ise_response.roles"
  cisco.ise.node_standalone_to_primary:
    ise_hostname: "{{ ansible_host }}"
    ise_username: "{{ ise_username | default( omit ) }}"
    ise_password: "{{ ise_password | default( omit ) }}"
    hostname: "{{ inventory_hostname }}" # must use hostname, not IP (ansible_host)
    ise_single_request_timeout: 120 # seconds
  register: ise_node_primary

  # Example response:
  # ```
  # ise_node_primary:
  #   changed: true
  #   failed: false
  #   ise_response:
  #     success:
  #       message: Node was updated successfully.
  #     version: 1.0.0
  #   result: Object updated
  # ```

- name: ISE Node `PrimaryAdmin` | {{ inventory_hostname }} ({{ ansible_host }})
  when: ise_node_primary.changed == True
  ansible.builtin.debug:
    msg: "ISE PPAN node is now '{{ inventory_hostname }}' ({{ ansible_host }})"
