---
# tasks file for roles/ise_version_assertion_⚠

- name: Get ISE Version | {{ inventory_hostname }} ({{ ansible_host }})
  cisco.ise.patch_info:
    ise_hostname: "{{ ansible_host }}"
    ise_username: "{{ ise_username | default( omit ) }}"
    ise_password: "{{ ise_password | default( omit ) }}"
  register: patch_info

- name: Set ise_version
  ansible.builtin.set_fact:
    ise_version: "{{ patch_info.ise_response.iseVersion }}"

- name: ISE Version Assertion
  ansible.builtin.assert:
    that: ise_version is version(version, '==')
    fail_msg: "{{ ise_version }} != {{ version }}"
    success_msg: "{{ ise_version }} == {{ version }}"
    quiet: true