---
# tasks file for roles/ise_policy_set_by_name

- name: Role Assertions
  ansible.builtin.assert:
    that:
      - key is defined
      - operator is defined
      - operator in OPERATORS
      - value is defined
  register: role_assertions

- name: Get All Network Access Policy Sets
  cisco.ise.network_access_policy_set_info:
    ise_hostname: "{{ ansible_host }}"
    ise_username: "{{ ise_username | default( omit ) }}"
    ise_password: "{{ ise_password | default( omit ) }}"
  register: policy_sets_info

# - name: List .name's
#   when:
#     - policy_sets_info is defined
#     - policy_sets_info.ise_response | count > 0
#   ansible.builtin.debug:
#     msg: "{{ policy_sets_info.ise_response | community.general.json_query('[].name') }}"

- name: Show All Policy Sets
  when:
    - policy_sets_info is defined
    - policy_sets_info.ise_response | count > 0
  delegate_to: localhost
  vars:
    hide: ['link','condition']
    maxw: 36
    rows: "{{ policy_sets_info.ise_response }}"
    temp: "{{ lookup('template', 'templates/list_of_dicts.j2') }}"
  ansible.builtin.debug:
    msg: "{{ temp }}"

- name: Filter By Condition | {{ key }} {{ operator }} {{ value }}
  when: 
    - policy_sets_info is defined
    - policy_sets_info.ise_response | count > 0
  ansible.builtin.set_fact:
    policy_sets: "{{ policy_sets_info.ise_response | selectattr(key, operator, value) | default([]) }} "

- name: Show `policy_sets`
  when:
    - policy_sets is defined
    - policy_sets | count > 0
  delegate_to: localhost
  vars:
    hide: ['link','condition']
    maxw: 36
    rows: "{{ policy_sets }}"
    temp: "{{ lookup('template', 'templates/list_of_dicts.j2') }}"
  ansible.builtin.debug:
    msg: "{{ temp }}"