---
# defaults file for roles/aws_ec2_ssh_keypair
ssh_key_directory: ~/.ssh
ssh_key_name: aws_ec2_ssh_keypair
ssh_key_private_file: "{{ ssh_key_directory }}/{{ ssh_key_name }}.pem"
ssh_key_public_file: "{{ ssh_key_directory }}/{{ ssh_key_name }}.public.pem"
