---
# defaults file for roles/ise_login_await
wait_state: started # Port is open
wait_delay: 0 # Default: 0. Seconds to delay before start and between retries
wait_sleep: 10 # Default: 1. Seconds to sleep between checks
wait_timeout: 2400 # Default: 300. Stop checking after <seconds>
wait_retries: 1000
wait_uri_timeout: 3 # seconds
wait_validate_certs: no
