---
# tasks file for roles/aws_ec2_show

- name: Show EC2 Instance Filters
  ansible.builtin.debug: 
    var: ec2_filters
    verbosity: 0

# - name: Get AWS EC2 VPC
#   delegate_to: localhost
#   amazon.aws.ec2_vpc_net_info:
#     # region: "{{ region | default(omit) }}"
#     filters:
#       "tag:project": "{{ project_name }}"
#   register: vpc

# - name: Show VPC
#   ansible.builtin.debug: 
#     var: vpc.vpcs
#     verbosity: 0

- name: Get AWS EC2 Instances
  delegate_to: localhost
  amazon.aws.ec2_instance_info:
    filters: "{{ ec2_filters | default({}) }}"
  register: ec2

- name: Show EC2 ISE Instances
  ansible.builtin.debug: 
    var: ec2.instances
    verbosity: 1

- name: Show AWS EC2 Instances Table
  delegate_to: localhost
  when:
    - ec2 is defined
    - ec2.instances is defined
    - ec2.instances | count > 0
  vars:
    head: "{{ show_head }}"
    hide: "{{ show_hide }}"
    maxw: "{{ show_maxw }}"
    rows: "{{ ec2.instances | flatten }}"
    temp: "{{ lookup('template', 'list_of_dicts.j2') }}"
  ansible.builtin.debug:
    msg: "{{ temp }}"
