---
# defaults file for roles/ise_repository_filenames
ise_repository_name: "{{ lookup('env','ISE_REPOSITORY_NAME') }}" # ISE repository name
ANY: "." # use . instead of * to match anything
FILTER_ISE_CONFIGS: '.+.gpg$'
filter: "{{ ANY }}" 